### PR TITLE
Fixes of WinAPI calls and some return-compare errors

### PR DESCRIPTION
**Pull request by oktonion**

### CODE REVIEW

**Comment by oktonion** [comment]
Oops, my bad for the first fix (7935630), I was wrong. Redone in 6586572.

**Comment by oktonion** [comment]
what about https://github.com/boostorg/interprocess/pull/110/commits/771e849faecdd4136dcd2fcea8c463144a1cde2f ?

**Comment by igaztanaga** [comment]
Hi, for the moment I prefer not to apply it as usually those wrappers maintain the argument count of the Windows API. Thanks again.

**Comment by oktonion** [comment]
> 
> 
> Hi, for the moment I prefer not to apply it as usually those wrappers maintain the argument count of the Windows API. Thanks again.

NP, just pointing out that those wrapped WinAPI functions "reserved" params could be changed in future by MS and my fix does not change wrapper params count. However if some boost codebase end-user has passed (by mistake) reserved param (anything except zero) to the wrappers my fix would prevent misuse of WinAPI function call when MS will decide this parameter appliance.

In my view this is safer but it is up to maintainers to decide what is right approach there. Thanks for review anyway. =)

**Pull request merged**
